spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE #메모리 DB
    # jdbc:h2:file:/tmp/testdb - 파일 DB
    username: sa
    password: 